name: Playwright Tests
on:
  push:
    branches: [ github_actions_demo ]
  pull_request:
    branches: [ github_actions_demo ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Build & Install
        run: mvn -B install -D skipTests --no-transfer-progress
      - name: Install Playwright
        run: mvn exec:java -e -D exec.mainClass=com.microsoft.playwright.CLI -D exec.args="install --with-deps"
      - name: Run tests
        run: mvn test -DAPI_KEY=${{ secrets.API_KEY }} -DUI_URL=${{ vars.UI_URL }}